server:
  port: 8083

#JWT
jwt:
  encryption:
    secret: oui2er43hn8934vby39
  access:
    token:
      expiration:
        seconds: 7200
  refresh:
    token:
      expiration:
        seconds: 21600

#OnlyDev
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  #Database
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service_db
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    username: postgres
    password: qweqwe
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Almaty

#Eureka
eureka:
  instance:
    appname: auth-service
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    register-with-eureka: false
    fetchRegistry: false
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone:  http://entry-eureka-server.kz:9000/eureka
